name: compile_and_test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test Lamscript on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++-12 ]
        include:
          - os: ubuntu-latest
            compiler: g++-12
            target: linux

          - os: macos-latest
            compiler: g++-12
            target: macos

          - os: windows-latest
            compiler: g++
            target: windows

    steps:
      - name: Install GTK for Linux
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
            sudo apt-get install -y libgtk-3-dev
          # sudo reboot
      - name: Install GTK for MacOS
        if: ${{ matrix.os == 'macos-latest'}}
          
        run: |
          # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install gtk+3
      - name: Install GTK for Windows
        if: ${{ matrix.os == 'windows-latest'}}
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: |
            mingw-w64-x86_64-openssl
            base-devel gcc vim cmake
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gtk3
          run: |
            ./scripts/build.sh \
            --build Release \
            --cpp_compiler ${{ matrix.compiler }} \
            --os ${{ matrix.target }}
            --cores 2
          #   pacman -S 
          #   pacman -S 
          #   pacman -S h
        

      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Run the projects setup.
      #   run: ./scripts/setup.sh --within-ci true

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a release build of lamscript
        run: ./scripts/build.sh \
            --build Release \
            --cpp_compiler ${{ matrix.compiler }} \
            --os ${{ matrix.target }}
            --cores 2
      
      # - name: Add builds to download folder
      #   run: |
      #     # cd downloads
            
      #       mkdir downloads
            
      #       sudo mv build ${{ github.workspace }}/downloads
      #       ls
      #       cd downloads
      #       ls

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download-${{ matrix.os }}
          path:  ${{ github.workspace }}/build
            

